streamer:
  sources:
    - type: "screen"
      id: "window_region"
      params:
        display_idx: 0
        fps: 30
        region: [0, 0, 1920, 1080]
        use_mss: False
    - type: "screen"
      id: "window_fullscreen"
      params:
        display_idx: 0
        fps: 30
        full_screen: True
        use_mss: False
    - type: "screen"
      id: "yuanshen"
      params:
        window_title: '原神'
        display_idx: 0
        fps: 30
        use_mss: False
        remove_title_bar: True
    - type: "screen"
      id: "zzz"
      params:
        window_title: '绝区零'
        display_idx: 0
        fps: 30
        use_mss: True

    - type: "camera"
      id: "webcam"
      params:
        camera_idx: 0
        resolution: [1280, 720]
        fps: 25

    - type: "camera"
      id: "ip_camera"
      params:
        url: "rtsp://192.168.1.100:554/stream"

  active_source: "yuanshen"
  stream_url: "rtmp://server/live/stream"
  bitrate: 2500000