streamer:
  sources:
    - type: "video_file" # 视频
      id: "video_player"
      enable: True
      params:
#        video_path: 'I:\genshin_video\character_show'
        video_path: 'sample_video'
        auto_play_next: True # 是否自动循环播放全部视频
        auto_crop_center: True # 是否自动裁边居中
        random_play: True # 是否开启乱序循环播放
#        first_play_video: 'xinhai.mp4'  # 指定第一个播放的视频
        fps: 30
    - type: "screen" # 区域截图
      id: "window_region"
      params:
        display_idx: 0
        fps: 30
        region: [684, 330, 300, 300]
        use_mss: False
    - type: "screen"  # 全屏截图
      id: "window_fullscreen"
      params:
        display_idx: 0
        fps: 30
        use_mss: False
    - type: "screen"  # 按窗口截图
      id: "yuanshen"
      params:
        window_title: '原神'
        display_idx: 0
        fps: 30
        use_mss: False
        remove_title_bar: True
    - type: "screen"  # 按窗口截图（use_mss=True兼容模式)
      id: "zzz"
      params:
        window_title: '绝区零'
        display_idx: 0
        fps: 30
        use_mss: True

    - type: "camera" # 相机
      id: "webcam"
      enable: false
      params:
        camera_idx: 0
        resolution: [1280, 720]
        fps: 25

    - type: "rtsp" #rtsp
      id: "my_mobile_phone_rtsp_camera"
      enable: false
      params:
        rtsp_url: "rtsp://admin:admin@192.168.30.134:8554/live"
        buffer_size: 5000
        timeout: 3

  active_source: "video_player"
  stream_url: "rtmp://server/live/stream"
  bitrate: 2500000